export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

export const DEL_CATEGORY_SUCCESS = 'DEL_CATEGORY_SUCCESS';